config/routes.rb
Beweek3::Application.routes.draw do

  root :to => "index#index"

  devise_for :users, controllers: { omniauth_callbacks:  "omniauth_callbacks" }

  match "/ws", :to => WebsocketRails::ConnectionManager.new

  match 'auth' => 'application#auth', :as => :auth
  match 'reg' => 'application#reg', :as => :reg
  match 'forget' => 'application#forget', :as => :forget
  match 'create' => 'application#create_company', :as => :create
  match 'out' => 'application#out', :as => :out
  match 'get_users' => 'application#get_users'
  match 'ajax/:action' => 'ajax'
  match 'download/:id' => 'download#file'

  match 'payment/:action' => 'payment'

  match '*path' => 'index#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def get_companies
    if user_signed_in?
      if current_user.active.to_i != 1
        redirect_to :auth and return
      end
      if params[:c].to_i > 0
        current_user.update_attribute :last_company, params[:c]
        redirect_to :root and return
      end
      @companies = current_user.companies
      if @companies
        cids = @companies.map {|c| c.id.to_i}
        if current_user.last_company.to_i > 0
          c_id = current_user.last_company.to_i
        else
          c_id = @companies.first.id
          current_user.update_attribute :last_company, c_id
        end
        if c_id.in? cids
          @company = @companies.find(c_id)
        else
          @company = @companies.first
          current_user.update_attribute :last_company, c_id
        end
        @connection = current_user.user_companies.where("user_companies.company_id = ?", @company.id).first
      else
        redirect_to :profile and return
      end
    end
  end

  def signed_in
    if user_signed_in?
      if current_user.active.to_i != 1
        redirect_to :auth and return
      end
    else
      redirect_to :auth and return
    end
  end

  def reg
    if user_signed_in?
      redirect_to :root and return
    else
      if params[:user]
        if params[:user][:email].match(/^[+a-z0-9_.-]+@[a-z0-9.-]+\.[a-z]{2,6}$/i)
          if User.where(:email => params[:user][:email]).exists?
            flash.now[:alert] = t(:user_already_registered)
          else
            code = Digest::SHA1.hexdigest(Time.now.to_s)
            cr = 1 # params[:cr] ? params[:cr].to_i : 0
            pass = ('a'..'z').to_a.shuffle.first(6).join
            Notify.registration(params[:user][:email], pass, code, cr).deliver
            user = User.create({
                                   :email => params[:user][:email],
                                   :password => pass,
                                   :active => 0
                               })
            Invite.create({
                              :user_from => 0,
                              :user_to => user.id,
                              :to => params[:user][:email],
                              :code => code,
                              :company_id => 0,
                              :expire => 1.month.from_now,
                              :cr => cr
                          })
            render :reg_success, :layout => false and return
          end
        else
          flash.now[:alert] = t(:wrong_format_email)
        end
      end
    end
    render :reg, :layout => false
  end

  def forget
    if user_signed_in?
      redirect_to :root and return
    else
      if params[:user]
        if params[:user][:email].match(/^[+a-z0-9_.-]+@[a-z0-9.-]+\.[a-z]{2,6}$/i)
          if User.where(:email => params[:user][:email]).exists?
            pass = ('a'..'z').to_a.shuffle.first(6).join
            Notify.forget(params[:user][:email], pass).deliver
            user = User.find_by_email(params[:user][:email])
            user.update_attribute :password, pass
            render :reg_success, :layout => false and return
          else
            flash.now[:alert] = t(:user_not_registered)
          end
        else
          flash.now[:alert] = t(:wrong_format_email)
        end
      end
    end
    render :forget, :layout => false
  end

  def auth
    if params[:i]
      inv = Invite.find_by_code(params[:i])
      if inv
        if inv.cr.to_i == 1
          u = User.find_by_email(inv.to)
          if u && u.active.to_i != 1
            u.update_attribute :active, 1
            company = Company.create({
                                         :name => u.email.to_s + " & company",
                                         :user_id => u.id
                                     })
            UserCompany.where({access: 2, company_id: company.id, user_id: u.id}).first_or_create
            sign_in u
            inv.update_attribute :activated, 1
            redirect_to :root and return
          else
            flash.now[:alert] = t(:wrong_invite_code)
          end
        else
          u = User.find_by_email(inv.to)
          if u
            if u.active.to_i != 1
              u.update_attribute :active, 1
            end
            sign_in u
            inv.update_attribute :activated, 1
            UserCompany.where({access: 0, company_id: inv.company_id, user_id: u.id}).first_or_create
            redirect_to :root and return
          else
            pass = ('a'..'z').to_a.shuffle.first(6).join
            Notify.registr(inv.to, pass).deliver
            u = User.create({
              :email => inv.to,
              :password => pass,
              :active => 1
            })
            sign_in u
            inv.update_attribute :activated, 1
            UserCompany.where({access: 0, company_id: inv.company_id, user_id: u.id}).first_or_create
            redirect_to :root and return
          end
        end
      end
    end
    if user_signed_in?
      if current_user.active.to_i != 1
        flash.now[:alert] = t(:unactive_user)
      else
        if params[:i]
          inv = Invite.find_by_code(params[:i])
          if inv
            if inv.company_id.to_i > 0 && inv.to == current_user.email && inv.activated.to_i != 1
              inv.update_attribute(:activated, 1)
              UserCompany.where({access: 0, company_id: inv.company_id, user_id: current_user.id}).first_or_create
              redirect_to :root and return
            end
            if inv.cr.to_i == 1
              user = User.find_by_email(inv.to)
              if user
                if user.email != current_user.email
                  sign_out
                  sign_in user
                end
                user.update_attributes :active, 1
                company = Company.create({
                                             :name => user.email.to_s + " & company",
                                             :user_id => user.id
                                         })
                UserCompany.where({access: 2, company_id: company.id, user_id: user.id}).first_or_create
              else
                flash.now[:alert] = t(:wrong_invite_code)
              end
            end
          else
            flash.now[:alert] = t(:wrong_invite_code)
          end
        end
      end
    else
      if params[:user]
        if params[:user][:email].match(/^[+a-z0-9_.-]+@[a-z0-9.-]+\.[a-z]{2,6}$/i) && params[:user][:password].length > 5
          user = User.find_by_email(params[:user][:email])
          if user
            if user.active.to_i != 1
              flash.now[:alert] = t(:unactive_user)
            else
              if user.valid_password?(params[:user][:password])
                #if params[:invite]
                #  inv = Invite.find_by_code(params[:invite])
                #  if inv && inv.to == params[:user][:email] && inv.activated.to_i != 1
                #    if inv.cr.to_i == 1
                #      u = User.find_by_email(inv.to)
                #      if u
                #        u.update_attributes :active, 1
                #        company = Company.create({
                #                                     :name => u.email.to_s + "'s company",
                #                                     :user_id => u.id
                #                                 })
                #        UserCompany.where({access: 2, company_id: company.id, user_id: u.id}).first_or_create
                #        sign_in u
                #        redirect_to :root and return
                #      else
                #        flash.now[:alert] = t(:wrong_invite_code)
                #      end
                #    else
                #      UserCompany.where({access: 0, company_id: inv.company_id, user_id: user.id}).first_or_create
                #    end
                #  end
                #end
                sign_in user
                redirect_to :root and return
              else
                flash.now[:alert] = t(:wrong_email_or_password)
              end
            end
          else
            flash.now[:alert] = t(:wrong_email_or_password)
            #user = User.create(:email => params[:user][:email], :password => params[:user][:password])
            #if params[:invite]
            #  inv = Invite.find_by_code(params[:invite])
            #  if inv && inv.to == params[:user][:email] && inv.activated.to_i != 1
            #    UserCompany.where({access: 0, company_id: inv.company_id, user_id: user.id}).first_or_create
            #  end
            #end
            #sign_in user
            #redirect_to :root and return
          end
        else
          flash.now[:alert] = t(:enter_email_and_password)
        end
      end
    end
    @imail = ''
    if params[:i] && !user_signed_in?
      i = Invite.find_by_code(params[:i])
      if i && i.activated.to_i != 1
        @imail = i.to
      end
    end
    render :auth, :layout => false
  end

  def out
    if user_signed_in?
      sign_out current_user
    end
    redirect_to :auth
  end

  def create_company
    if user_signed_in?
      if params[:company]
        if params[:company][:name].length > 2
          if Company.where(:code => params[:company][:code]).exists?
            flash.now[:alert] = t(:company_code_already_exists)
          else
            company = Company.new(params[:company])
            company.user_id = current_user.id
            if company.save
              connection = UserCompany.new({:user_id => current_user.id, :company_id => company.id, :access => 2})
              if connection.save
                redirect_to :root and return
              end
            end
          end
        else
          flash.now[:alert] = t(:company_name_too_small)
        end
      end
    else
      redirect_to :auth and return
    end
    render :create_company, :layout => false

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
    devise_mapping.to
  end
end

app/views/application/auth.html.haml
!!!
%html.overflow_hidden
  %head
    %title Beweek2
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "auth"
    
    = csrf_meta_tags
    = yield(:head)
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};"
  %body.white_bg
    .container-fluid.clear_left_margin
      .content_block{:style => 'margin: 0 auto'}
        .book

          %div.form_el
            .img_logo
              %img{:src => 'assets/theme_1/big_logo.png', :title => '', :width => '371', :height => '80'}
              %p.error= flash[:alert]
            .form_el_bg

              - if user_signed_in?
                %p
                  You are logged in as #{current_user.get_name}
                %p= link_to t(:logout), :out
              - else
                = form_tag '', :method => :post, :class => 'form-horizontal ', :id => 'auth_form' do
                  = hidden_field_tag 'invite', params[:i]
                  .control-group
                    //%label.control-label{:for => "inputEmail"}= t(:email)
                    .controls
                      %i.abs_pass Почта
                      = hidden_field_tag 'user[email]', @imail
                      = text_field_tag 'user[email]', @imail, :disabled => @imail.blank? ? false : true, :id => 'email'
                      %img.ico_mail{:src => 'assets/theme_1/ico_mail.png', :title => '', :width => '26', :height => '21'}
                  .control-group
                    //%label.control-label{:for => "inputPassword"}= t(:password)
                    .controls
                      %i.abs_pass Пароль
                      = password_field_tag 'user[password]'

                      %img.ico_pass{:src => 'assets/theme_1/ico_pass.png', :title => '', :width => '22', :height => '22'}
                  .control-group
                    .controls
                      %a.btn-link-dis{:href => :reg}= t(:signing_up)
                      %span.btn-link-dis &nbsp;|&nbsp;
                      %a.btn-link-dis{:href => :forget}= t(:forget)
                      %button.btn.btn-primary#auth_submit{:type => "submit"}= t(:sign_in)
                      %script
              - if devise_mapping.omniauthable?
                .auth_footer_form
                  %p Войти через социальные сети
                  .soc_btn
                    - resource_class.omniauth_providers.each do |provider|
                      = link_to omniauth_authorize_path(resource_name, provider) do
                        %div{:class => provider.to_s}

app/views/application/create_company.html.haml
!!!
%html
  %head
    %title Beweek2 create company
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", :media => "all"
    = csrf_meta_tags

    = yield(:head)
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};"
    = javascript_include_tag "create_company"

  %body
    .container-fluid.clear_left_margin
      .main-container.create_company
        .content_block
          .inner_first
            .inner_seccond
              .viewport.content_inner_viewport
                .overview
                  .create_company_plane
                    = form_tag :create, :method => :post do
                      -#.span3
                        %label.well
                          %h2.muted= t(:company_type_0)
                          -#%p
                            -#span.label POPULAR
                          %ul
                            %li Unlimited access with no limits
                            %li 100 MB of space

                          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
                          %hr
                            %h3 FREE
                          
                          = radio_button_tag 'company[type_id]', 0
                                  
                      .span3
                        %label.well
                          %h2.text-warning= t(:company_type_1)
                          -#%p
                            -#%span.label.label-success POPULAR
                          %ul
                            %li 1 GB of space
                            %li Unlimited access with no limits
                          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
                          %hr
                            %h3 1 490 / month
                
                          = radio_button_tag 'company[type_id]', 1
                             
                      .span3
                        %label.well
                          %h2.text-info= t(:company_type_2)
                          -#%p
                            -#%span.label.label-info BUDGET
                          %ul
                            %li 10 GB of space
                            %li Unlimited access with no limits
                          %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta.
                          %hr
                            %h3 9 990 / month
                          = radio_button_tag 'company[type_id]', 2
                      .forms_el
                        .lb 
                          %fieldset
                            .form-horizontal
                              %legend 
                                Создание компании

                              %p.error= flash[:alert]
                              .control-group
                                %label.control-label= t(:company_name)
                                .controls
                                  = text_field_tag 'company[name]'
                                  %span Длина не менее 3х символов
                              .control-group
                                %label.control-label= t(:company_description)
                                .controls
                                  = text_area_tag 'company[text]'
                              .control-group
                                %label.control-label= t(:company_code)
                                .controls
                                  = text_field_tag 'company[code]'    
                                  = '.beweek.ru'
                                  %span Длина не менее 3х символов
                              .control-group
                                %label.control-label
                                .controls.subm_btn
                                  = submit_tag t(:create_company)
                            .link_block
                              %legend 
                                %a.to_back{:href => 'javacript:;', :title => ''} Назад
                                = link_to t(:logout), :out

app/views/application/forget.html.haml
!!!
%html.overflow_hidden
  %head
    %title Beweek2
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "auth"

    = csrf_meta_tags
    = yield(:head)
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};"
  %body.white_bg
    .container-fluid.clear_left_margin
      .content_block{:style => 'margin: 0 auto'}
        .book

          %div.form_el.short_form_el
            .img_logo
              %img{:src => 'assets/theme_1/big_logo.png', :title => '', :width => '371', :height => '80'}
              %p.error= flash[:alert]
            .form_el_bg
              - if user_signed_in?
                %p
                  You are logged in as #{current_user.get_name}
                %p= link_to t(:logout), :out
              - else
                = form_tag '', :method => :post, :class => 'form-horizontal ', :id => 'auth_form' do
                  .control-group
                    //%label.control-label{:for => "inputEmail"}= t(:email)
                    .controls
                      %i.abs_pass Почта
                      = text_field_tag 'user[email]', @imail, :disabled => false , :id => 'email'
                      %img.ico_mail{:src => 'assets/theme_1/ico_mail.png', :title => '', :width => '26', :height => '21'}
                  -#.control-group
                    %label.control-label{:for => "inputPassword"}= t(:password)
                    .controls
                      = password_field_tag 'user[password]'
                  .control-group
                  .control-group

                    .controls
                      %a.btn-link-dis{:href => :auth}= t(:sign_in)
                      %span.btn-link-dis &nbsp;|&nbsp;
                      %a.btn-link-dis{:href => :reg}= t(:signing_up)
                      %button.btn.btn-primary#auth_submit{:type => "submit"}= t(:send_me_password)
                      %script
                -# if devise_mapping.omniauthable?
                  Войти через социальные сети
                  %br
                  - resource_class.omniauth_providers.each do |provider|
                    = link_to omniauth_authorize_path(resource_name, provider) do
                      %div{:class => provider.to_s}

app/views/application/reg.html.haml
!!!
%html.overflow_hidden
  %head
    %title Beweek2
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "auth"

    = csrf_meta_tags
    = yield(:head)
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};"
  %body.white_bg
    .container-fluid.clear_left_margin
      .content_block{:style => 'margin: 0 auto'}
        .book

          %div.form_el.short_form_el
            .img_logo
              %img{:src => 'assets/theme_1/big_logo.png', :title => '', :width => '371', :height => '80'}
              %p.error= flash[:alert]
            .form_el_bg

              - if user_signed_in?
                %p
                  You are logged in as #{current_user.get_name}
                %p= link_to t(:logout), :out
              - else
                = form_tag '', :method => :post, :class => 'form-horizontal ', :id => 'auth_form' do
                  .control-group
                    //%label.control-label{:for => "inputEmail"}= t(:email)
                    .controls
                      %i.abs_pass Почта
                      = text_field_tag 'user[email]', @imail, :disabled => false , :id => 'email'
                      %img.ico_mail{:src => 'assets/theme_1/ico_mail.png', :title => '', :width => '26', :height => '21'}
                  -#.control-group
                    %label.control-label{:for => "inputPassword"}= t(:password)
                    .controls
                      = password_field_tag 'user[password]'
                  .control-group.clear_block
                  .control-group

                    .controls
              
                      %a.btn-link-dis{:href => :auth}= t(:sign_in)
                      %span.btn-link-dis &nbsp;|&nbsp;
                      %a.btn-link-dis{:href => :forget}= t(:forget)
                      %button.btn.btn-primary#auth_submit{:type => "submit"}= t(:sign_up)
                      %script  
                -# if devise_mapping.omniauthable?
                  Войти через социальные сети
                  %br
                  - resource_class.omniauth_providers.each do |provider|
                    = link_to omniauth_authorize_path(resource_name, provider) do
                      %div{:class => provider.to_s}

app/views/application/reg_success.html.haml
!!!
%html.overflow_hidden
  %head
    %title Beweek2
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "auth"

    = csrf_meta_tags
    = yield(:head)
    = javascript_tag "var AUTH_TOKEN = #{form_authenticity_token.inspect};"
  %body.white_bg
    .container-fluid.clear_left_margin
      .content_block{:style => 'margin: 0 auto'}
        .book

          %div.form_el.only_error_success.short_form_el
            .img_logo
              %img{:src => 'assets/theme_1/big_logo.png', :title => '', :width => '371', :height => '80'}
              %p.error= flash[:alert]
              %p.success
                Вам отправлено письмо с дальнейшими инструкциями
                %br
                %br
                %a{:href => '/', :title => ''} Вернуться главную
            .form_el_bg